commit desafio react
ServerSoftwares/desafio-react-jr pull request #3
Opened 2022-04-08 18:24 UTC by WhiteMoscou

Sistema de busca de produtos em react.js

2022-04-08 18:26 UTC, WhiteMoscou commented
Foi uma ótima experiência, aprendi muitas coisas do backend e consegui identificar lacunas de aprendizagem que vão me ajudar a evoluir muito.

2022-04-08 18:31 UTC, toppermitz commented
Pode colocar o node_moduoles no `.gitignore` e comitar novamente por favor?

2022-04-08 21:22 UTC, WhiteMoscou commented
Node removido


Em sex., 8 de abr. de 2022 às 15:32, Anderson Dapper Rocha <
***@***.***> escreveu:

> Pode colocar o node_moduoles no .gitignore e comitar novamente por favor?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ServerSoftwares/desafio-react-jr/pull/3#issuecomment-1093185152>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APUXVO6JU4X33XZPC32H4BLVEB3SJANCNFSM5S5JXDYQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-04-11 12:56 UTC, toppermitz commented
@WhiteMoscou consegue dar uma revisada nesse teu projeto? Não está nem rodando

2022-04-11 15:16 UTC, toppermitz requested changes
Precisa revisar todo o projeto pois iniciando do zero (checkout novo) não há como fazer funcionar sem ter que mexer no código.

2022-04-11 15:16 UTC, toppermitz commented on react-back/Banco de Dados/server.js
> +});
O campo código é uma chave primaria. Logo ele deve ser usado no where pois ele é o identificador do produto.
Este campo nunca poderá ser alterado ou perderá a integridade do banco de dados.

2022-04-11 15:16 UTC, toppermitz commented on react-back/Banco de Dados/server.js
> +  });
o campo `codigo` é um autoincremento ele não deve ter seu valor informado dentro do insert. Até pq o front não tem como saber qual o código deveria ser

2022-04-11 15:16 UTC, toppermitz commented on react-front/desafio-react-jr/src/App.js
> +  };
Como não há nenhum tratamento de erro. E a implementação dos métodos pegam o values com propriedades que não existem. Simplesmente não faz nada e não mostra nem sequer q deu erro pra o usuário.

2022-04-12 18:27 UTC, WhiteMoscou commented
Boa tarde Anderson, desculpe a demora, conversei com a Jana, e informei o motivo da falta de resposta, vou refatorar o código todo.

2023-03-12 00:18 UTC, closed without merging